- prisma/seed.ts
- src/carts/carts.controller.ts
🐛 fix(seed): seed파일 env관련사항 수정
> 🐛 fix(seed): seed파일 env관련사항 수정

- prisma/seed.ts
> 🐛 fix(seed) : seed 파일 수정-2

- .github/workflows/deploy.yml
- SSH 연결 시 EC2_KEY_PAIR_TYPE을 비밀로 설정하여 보안 강화
- 배포 스크립트에서 민감한 정보 마스킹을 비밀로 변경
- SSH 명령어에서 비밀 변수를 사용하여 코드 일관성 유지
> 🔧 chore(deploy): SSH 키 페어 타입을 비밀로 관리하고 배포 스크립트 개선

- .github/workflows/deploy.yml
- SSH 명령어에 NVM 소스 추가하여 Node.js 환경 설정 보장
- 서버 로그 확인 시 로그 파일 출력 방식 개선
- PM2 상태 재확인 추가로 배포 안정성 향상
> 🔧 chore(deploy): 배포 스크립트에서 NVM 소스 추가 및 PM2 상태 확인 개선

- .github/workflows/deploy.yml
- SSH 연결 시 옵션 추가로 안정성 향상
- EC2 내부에서 건강 검사 수행 로직 추가
- 최대 재시도 횟수 및 대기 시간 설정으로 검증 과정 개선
- 서버 로그 및 방화벽 상태 확인 기능 추가
> 🔧 chore(deploy): 배포 검증 로직 개선 및 SSH 옵션 추가

- .github/workflows/deploy.yml
- .env 파일에 GIT_COMMIT_SHA 추가하여 배포 정보 기록
- 불필요한 마스킹 제거로 코드 간결성 향상
> 🔧 chore(deploy): GIT_COMMIT_SHA 환경 변수 추가 및 마스킹 제거

- src/main.ts
- src/order-requests/order-requests.service.ts
- `order-requests.service.ts` 파일에서 불필요한 공백을 제거하여 코드 가독성 향상
> Chore(swagger)/111-rename-backend-endpoint

- .github/workflows/deploy.yml
- 배포 스크립트에서 건강 검사 URL을 `/api/health`로 변경하여 API 엔드포인트에 맞춤
> 🔧 chore(deploy): 건강 검사 엔드포인트 수정

- .github/workflows/deploy.yml
- 환경 변수 복호화 실패 시 처리 로직 수정
- Prisma 스키마 배포 시 로그 출력 제한 및 필터링 추가
- 배포 성공 시 메시지 출력 추가
> 🔧 chore(deploy): 배포 스크립트 수정 및 Prisma 배포 로그 개선

- .github/workflows/deploy.yml
- 배포 스크립트에서 GPG_PASSPHRASE 변수 사용 방식 수정
- PM2 프로세스 정리 시 에러 메시지 개선
- 로그 마스킹 처리에서 특수 문자 이스케이프 추가
> 🔧 chore(deploy): 배포 스크립트 개선 및 로그 마스킹 처리 수정

- .github/workflows/deploy.yml
- PM2 상태 확인 시 환경 설정을 추가하여 올바른 경로와 설정을 보장
- EC2 내부에서 건강 검사 수행 시 필요한 환경 변수를 설정하도록 수정
> 🔧 chore(deploy): PM2 상태 확인 및 환경 설정 추가

- .github/workflows/deploy.yml
- PM2 실행 파일 경로 설정 및 검증 추가
- PM2 프로세스 정리 시 에러 메시지 개선
- PM2 시작 전 환경 검증 로직 추가
- EC2에서 PM2 명령어 사용 시 경로 설정 통일
> 🔧 chore(deploy): PM2 경로 설정 및 프로세스 관리 개선

- .github/workflows/deploy.yml
- NVM 설정 및 Node.js 버전 22 활성화 추가
- PM2 실행 시 필요한 환경 변수 설정 개선
- EC2에서 PM2 상태 확인 및 건강 검사 시 환경 설정 통일
> 🔧 chore(deploy): NVM 및 Node.js 환경 설정 추가

- .github/workflows/deploy.yml
- NVM 및 Node.js 관련 설정을 제거하여 스크립트를 간소화
- curl 요청 및 상태 코드 검증 로직을 개선하여 가독성 향상
- 재시도 로직에서 변수 사용 방식을 통일하여 일관성 유지
> 🔧 chore(deploy): 건강 검사 스크립트 개선 및 불필요한 NVM 설정 제거

- .github/workflows/deploy.yml
- SSH 명령어에서 문자열 구분자를 변경하여 가독성 향상
- curl 요청의 응답 처리 방식에서 작은 수정 적용
> 🔧 chore(deploy): 건강 검사 스크립트의 SSH 명령어 수정

- .github/workflows/deploy.yml
- PM2 설치를 위한 명령어 추가 및 설치 실패 시 에러 처리 개선
- PM2 경로 설정 방식을 `which pm2`로 변경하여 경로 검증 로직 간소화
- 건강 검사 스크립트에서 NVM 및 Node.js 활성화 관련 설정 추가
- curl 요청의 응답 처리 방식에서 변수 사용 방식을 통일하여 일관성 유지
> 🔧 chore(deploy): PM2 설치 및 경로 설정 개선

- .github/workflows/deploy.yml
- Node.js 환경 설정을 위한 NVM 초기화 및 버전 설정 추가
- pnpm 설치 확인 및 설치 로직 추가
- curl 요청의 응답 처리 방식에서 문자열 구분자 변경
- 환경 변수 설정 방식을 일관성 있게 수정
> 🔧 chore(deploy): Node.js 및 pnpm 환경 설정 추가

- .github/workflows/deploy.yml
- pnpm setup 실행 및 실패 시 에러 처리 추가
- PNPM_HOME 및 PATH 환경변수 설정 및 .bashrc에 영구 적용 로직 추가
- 현재 셸에 환경변수 적용을 위한 source 명령어 추가
> 🔧 chore(deploy): pnpm 환경 설정 및 영구 적용 추가

- .github/workflows/deploy.yml
- pnpm 설치 확인 및 설치 로직을 제거하고, SHELL 환경 변수를 bash로 설정하는 로직 추가
- pnpm 설치가 이미 되어 있다는 가정 하에 불필요한 설치 과정을 간소화
> 🔧 chore(deploy): SHELL 환경 변수 설정 및 pnpm 설치 로직 제거

- .github/workflows/deploy.yml
- pnpm 설치 확인 로직에서 설치 과정을 간소화하고, 기존 pnpm 환경변수를 로드하는 로직 추가
- PNPM_HOME이 설정되어 있지 않은 경우에만 pnpm setup을 실행하도록 변경
- PATH에 pnpm 경로가 없는 경우에만 추가하여 중복 설정 방지
> 🔧 chore(deploy): pnpm 설치 로직 개선 및 환경변수 설정 최적화

- .github/workflows/deploy.yml
- pnpm 환경변수 설정을 명확히 하고, 중복된 환경변수 로드 로직을 제거하여 코드 간소화
- PATH에 pnpm 경로 추가 및 기존 환경변수 로드 로직을 통합하여 가독성 향상
> 🔧 chore(deploy): pnpm 환경변수 설정 및 중복 로직 제거

- .github/workflows/deploy.yml
- Node.js 버전 설정을 매트릭스로 변경하여 유연성 향상
- PNPM_HOME 및 PATH 환경변수 경로를 업데이트하여 일관성 유지
> 🔧 chore(deploy): Node.js 버전 매트릭스 추가 및 pnpm 환경변수 경로 수정

- .github/workflows/deploy.yml
- Node.js 버전 설정을 매트릭스에서 고정값으로 변경하여 간소화
- pnpm 설치 로직을 통합하고, 불필요한 설치 과정을 제거하여 효율성 향상
- 새로운 의존성 설치 단계 추가로 배포 과정 개선
> 🔧 chore(deploy): Node.js 설정 및 pnpm 설치 로직 정리

- .github/workflows/deploy.yml
- curl 요청 시 변수 사용을 이스케이프 처리하여 안정성 향상
- PNPM_HOME 및 PATH 환경 변수 설정을 명확히 하여 가독성 개선
- 서버 상태 확인 로직에서 echo 문을 수정하여 일관성 유지
> 🔧 chore(deploy): curl 요청 및 환경 변수 설정 개선

- .github/workflows/deploy.yml
- PM2 경로 설정을 간소화하고, pm2 명령어로 변경하여 가독성 향상
- 건강 검사 로직을 명확히 하여 코드 일관성 유지
- SSH 연결 시 환경 변수 설정을 명확히 하여 안정성 향상
> 🔧 chore(deploy): 건강 검사 및 환경 변수 설정 개선

- .github/workflows/deploy.yml
- PM2 상태 확인을 위한 SSH 명령어 블록을 제거하여 배포 스크립트 간소화
- 서버 상태 확인 로직은 유지하여 일관성 유지
> 🔧 chore(deploy): PM2 상태 확인 로직 제거 및 코드 간소화

- .github/workflows/deploy.yml
* [환경 변수 검증 및 Prisma 시딩 로직 개선](https://github.com/snack-25/back/commit/e8649285040be19ad21c7359e65d330b6e46bd77)
> Fix(deploy)/146 add seeding process

- .github/workflows/deploy.yml
- 환경 변수 검증을 배열 반복문에서 개별 조건문으로 변경하여 가독성 향상
- GIT_COMMIT_SHA 검증 추가로 배포 안정성 강화
> 🔧 chore(deploy): 환경 변수 검증 로직을 개별 체크로 변경

- src/main.ts
- 허용된 출처에 Amplify 추가
- 허용된 헤더 및 노출된 헤더 목록 추가로 CORS 정책 강화
> 🔧 chore(cors): CORS 설정 업데이트

- package-lock.json
- prisma/schema/Product.prisma
- prisma/schema/User.prisma
- prisma/schema/Wishlist.prisma
- src/app.module.ts
- src/wishlist/dto/create-wishlist.dto.ts
- src/wishlist/entities/wishlist.entity.ts
- src/wishlist/wishlist.controller.spec.ts
- src/wishlist/wishlist.controller.ts
- src/wishlist/wishlist.module.ts
- src/wishlist/wishlist.service.spec.ts
- src/wishlist/wishlist.service.ts
- test.http
🐛 fix(api) : wishlist_module prismamodule설정 추가
> 🐛 fix(api) : wishlist_module prismamodule설정 추가

- prisma/const/orderRequestItems.ts
- prisma/seed.ts
- src/shared/swagger/SwaggerOptions.ts
- 주문 요청 ID 및 아이템 ID를 동적으로 생성하도록 변경
- 사용자 및 카테고리 ID를 생성하는 로직 추가
- Swagger 문서에 찜 관리 태그 추가
> ✨ feat(prisma): 주문 요청 및 사용자 데이터 시드 개선

- .github/workflows/deploy.yml
- `pnpm install` 명령어에서 `--frozen-lockfile` 플래그 제거
- 의존성 설치 시 dev 의존성 제외 및 pre/post 스크립트 실행 제외 유지
> 🚀 ci(deploy): 의존성 설치 스크립트 수정

- .github/workflows/deploy.yml
- 백업 파일 생성 후 최신 백업 파일을 제외한 모든 `backup-*.tar.gz` 파일 삭제 추가
- 배포 시 백업할 파일이 없을 경우 사용자에게 안내 메시지 추가
> 🚀 ci(deploy): 배포 스크립트 백업 로직 개선

- src/auth/auth.guard.ts
> 🐛 fix: 배포에러 해결 테스트

- src/auth/auth.guard.ts
> 🐛 fix: 배포에러 해결 테스트-2

- src/auth/auth.guard.ts
> 🐛 fix: 배포에러 해결 테스트-3

- package.json
- pnpm-lock.yaml
- prisma:seed:prod 명령어에서 ts-node를 npx로 변경
- @nestjs/cli, ts-node 등 패키지 버전 업데이트
> 🔧 chore: package.json 및 pnpm-lock.yaml 수정

- package.json
- pnpm-lock.yaml
- typescript 패키지 버전 5.8.2로 추가
- pnpm-lock.yaml에서 typescript 관련 정보 업데이트
> 🔧 chore: package.json 및 pnpm-lock.yaml에 typescript 추가

- prisma/seed.ts
- zipcode 테이블의 데이터를 삭제하기 전에 company_addresses 테이블의 참조를 먼저 처리
- 데이터 해시 비교 후 변경에 따라 zipcodeId를 null로 설정하고, zipcode 테이블 데이터 삭제 후 새 데이터 추가
> 🐛 fix: 우편번호 데이터 처리 로직 개선

- prisma/seed.ts
- companyAddress 생성 방식을 for 루프에서 createMany로 변경하여 성능 개선
- company 필드에서 companyId로 변경하고, zipcode 필드를 zipcodeId로 수정하여 데이터 구조 일관성 유지
> 🐛 fix: companyAddress 생성 방식 및 데이터 구조 변경

- prisma/seed.ts
- CUID2 형식 검증 함수를 추가하여 잘못된 ID를 가진 Budget 데이터를 찾아 삭제
- 유효한 ID를 가진 새로운 Budget 데이터만 추가하도록 로직 수정
- 모든 Budget 데이터가 유효할 경우 추가하지 않도록 로그 메시지 변경
> 🐛 fix: Budget 데이터 ID 검증 및 잘못된 데이터 삭제

- prisma/seed.ts
- 각 사용자에 대해 장바구니를 하나씩 추가하도록 로직 수정
- 기존 장바구니 데이터 삭제 후 새로운 데이터 일괄 생성
- 중복된 데이터는 건너뛰도록 설정
> 🐛 fix: 장바구니 데이터 추가 로직 개선

- prisma/seed.ts
> 장바구니 시딩 로직 개선 및 upsert로 변경

- src/orders/orders.controller.ts
- src/orders/orders.service.ts
> 🐛 fix : 주문조회 드롭다운 수정

- src/orders/orders.service.ts
> 🐛 fix : 빌드에러 해결

- src/users/dto/get-user-list-params.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
> [back]🐛  fix: 같은 회사 회원들만 리스트 하게 수정

- src/auth/auth.service.ts
> ♻️ feat(auth): 비밀번호 검증 추가 및 오류 처리 개선
